/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xB8nK2mR3fd
 */
import { Input } from "@/components/ui/input"

export default function SarchBar() {
  return (
    (<div key="1" className="flex flex-col items-center min-h-screen py-9">
      <div className="p-1">
        <div className="p-2 bg-white rounded-lg shadow-sm dark:bg-gray-950">
          <Input placeholder="Search for movies, series, and more..." type="search" />
        </div>
      </div>
    </div>)
  );
}